markdown: kramdown
permalink: /:year/:month/:day/:title
lsi: true
highlighter: rouge

exclude: [README.markdown, todo.org, deploy.sh]

algolia:
  application_id: "K4MUG7LHCA"
  index_name: "prod_beatletech"
  search_only_api_key: "2b61f303d605176b556cb377d5ef3acd"
  files_to_exclude:
    - blog.html
    - cases.html
    - setup.html
    - archive.html
    - index.html
    - not-found-404.html

url: https://beatletech.com

plugins:
  - jekyll-redirect-from

collections:
  cases:
    output: true
    sort_by: year
    permalink: /case/:name
