markdown: kramdown
permalink: /:year/:month/:day/:title
lsi: true
highlighter: rouge

exclude: [ README.markdown, todo.org, deploy.sh ]

algolia:
  application_id: 'K4MUG7LHCA'
  index_name: 'prod_beatletech'
  search_only_api_key: '2b61f303d605176b556cb377d5ef3acd'
  files_to_exclude:
    - blog.html
    - setup.html
    - archive.html
